### ISSUE TITLE
ONNXRuntimeError

### ISSUE THREAD

**Issue by onexuan** [daquexian/onnx-simplifier#27]
MAC python3,  onnx-simplifier 1.8 onnxruntime 0.5.0
  
File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 24, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/onnxsim/__main__.py", line 17, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 200, in simplify
    res = forward_all(model_opt)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 107, in forward_all
    res = forward(model)
  File "/usr/local/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 99, in forward
    res = OrderedDict(zip(outputs, sess.run(outputs, inputs)))
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /Users/vsts/agent/2.155.1/work/1/s/onnxruntime/core/providers/cpu/nn/pool_base.h:169 std::vector<int64_t> onnxruntime::PoolBase::SetOutputSize(const onnxruntime::TensorShape &, int64_t, std::vector<int64_t> *, const std::vector<int64_t> &, int64_t) const input_shape.Size() > 0 was false.

**Comment by daquexian** [comment]
Thanks for your report! Could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by onexuan** [comment]
Hi I have sent to you

**Comment by daquexian** [comment]
Fixed in #28

**Comment by daquexian** [comment]
Please upgrade your onnxsim to v0.1.9, and use `--input-shape xxxx` to set input shape manually. Try `python3 -m onnxsim -h` for the details

**Comment by onexuan** [comment]
But I try it, I still can't set --input-shape.
Input:
id:input_1:0
type: float32[unk__519,224,224,3]

error:
__main__.py: error: unrecognized arguments: -input-shape input_1:0,224,224,3

Please help

**Comment by daquexian** [comment]
@onexuan It is double dash '--', not '-'

**Comment by UJWALA-SANKH** [comment]
can somebody tell what is the --input-shape value should we give to simplify the mask_rcnn.onnx model?
